
#ifndef DECEN_OBJ_H_
#define DECEN_OBJ_H_

#include "OBJECT_MACRO.h"
#include "CHILD_OBJ.h"

#define DECEN_OBJ_PUBLIC_MEMBER_\
		int decendent_data;

#define DECEN_OBJ_PRIVATE_MEMBER_\


#define DECEN_OBJ_PUBLIC_METHOD_(PREFIX,MACRO_X)\

#define DECEN_OBJ_PRIVATE_METHOD_(PREFIX,MACRO_X)\

#define DECEN_OBJ_OVERRIDE_METHOD_(PREFIX,MACRO_X)\
        MACRO_X(PREFIX,int,GetPublic, DECEN_OBJ* a)\


OBJECT_INHERIT_DECLARE(DECEN_OBJ,CHILD_OBJ)

#define DECEN_OBJ_INH_  \
        CHILD_OBJ_INH_\
        OBJECT_INHERIT_STRUCT_PRIDELCAREX_(DECEN_OBJ)



#endif

